### ISSUE TITLE
how to use windef with images that are not in settings

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv-python#121]
@TKaeufer - could you please add an example how to use windef when images are already loaded and not provided as file path in settings. e.g. sometimes I'd like to work with movies and I use `pims.Video` to read those - it's much more convenient that converting it to frames and storing as images. 

Thanks
Alex

**Comment by TKaeufer** [comment]
Hey Alex, you talking about using a video that is already loaded into the workspace?  Right now windef uses the "func" as in tutorial2.py to read the frames AND there is no way to process videos without modification of the windef code. If you share the code you use to read the videos with me, I might add this function to the windef.py and to the settings. But it might take some time. since im pretty bussy right now ;).

**Comment by alexlib** [comment]
the main request here is to make a function, e.g. `windef.piv(I,J,settings)` that will take I,J as inputs and not path to the images. Basically it means that you could split the code of reading files from the processing .

**Comment by TKaeufer** [comment]
Ok, now I understand what you are looking for. I'll work on this.

**Comment by alexlib** [comment]
it would be also great to have some demo case - e.g. as the one in your report or similar - that shows the effect of parameters in Settings. e.g. number of passes, etc. especially for the noisy or low quality image sets.

**Comment by alexlib** [comment]
solved many times, see examples and the GUI that all `windef.first_pass` and `windef.multi_pass` separately.
