### ISSUE TITLE
Uncertainty quantification

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv-python#205]
Uncertainty using the published method, as in PIVLab

https://github.com/Shrediquette/PIVlab/issues/58#issue-913569552

**Comment by alexlib** [comment]
https://github.itap.purdue.edu/PavlosVlachosGroup/meta-uncertainty

**Comment by lento234** [comment]
Hi @alexlib 

I have a working implementation of UQ by image matching (https://doi.org/10.1088/0957-0233/24/4/045302). It's a direct python re-implementation of http://piv.de/uncertainty/UncertaintyCodes/ParticleDisparity_Code.zip. The notebook (https://github.com/lento234/pivuq/blob/main/examples/06_uncertainty_quantification_SWS_testdata.ipynb) shows quite a well agreement with the original code, I think. 

I would like to contribute and am interested in adding it to the `openpiv` package. Would you be interested in it in as well? If so, how should I move forward? Do you have any specific API design in mind? Or is there any already some works done in this regard already which I could assist. 

Best,
Lento

**Comment by alexlib** [comment]
Hi @lento234 

I've seen your `pivuq` work and it looks great. Your contribution would be great. If I understand correctly we need to run this sort of test on the test cases of openpiv - so we'd kind of adding an uncertainty column to every PIV map.
The interface, I believe should be quite simple: 

1. user runs the OpenPIV - in Matlab, Python or C++, saves the data. 
2. We add data readers and translators from all these to `pivuq` and store additional column to every file
3. We add some ways to create plots, histograms, etc. as you did, using those files with UQ

Do you have another idea? Do you think about integrating UQ into the PIV process itself and creating UQ data on the fly? I'm afraid this can increase significantly the run time and should be, if at all, an option.

**Comment by lento234** [comment]
Hi @alexlib 

Initially I was thinking something more in the lines of `openpiv.uq` module which would contain the UQ functions need to do the calculations. However, perhaps the interface as you proposed perhaps makes more sense. In that way, the UQ can be modular, and you can opt to run PIV processing as you wish (in MATLAB, python, or perhaps even alternative PIV code). 

In future though, I would be not be opposed to incorporating the UQ directly into the PIV process step (of course as optional as you mentioned). A rough benchmark shows that it would add a couple more seconds to the analysis (per image pair). 

I will have a look at the test cases of openpiv. And see how to incorporate similar tests to `pivuq`. I will look into the data reader and translators, and looking having an IO module. The idea will be to have a generic data format, so it will not be hard to process / plot as one wishes.

Best,
Lento

**Comment by alexlib** [comment]
`openpiv.uq` sounds great. Let's merge the work into a separate repo fork of `openpiv` and when it's ready, release as 0.3 :)

**Comment by alexlib** [comment]
I asked you about the two specific columns present in the DAT file you used - what are those columns after `x,y,u,v`? we need to generate them first by `openpiv`, which also means that we need to change a bit the reading/writing of the data output. Since this is used by other post-processing routines, I believe it has to be done carefully, keeping `uq` optional.

**Comment by lento234** [comment]
> `openpiv.uq` sounds great. Let's merge the work into a separate repo fork of `openpiv` and when it's ready, release as 0.3 :)

Sounds good :). 

> I asked you about the two specific columns present in the DAT file you used - what are those columns after `x,y,u,v`? we need to generate them first by `openpiv`, which also means that we need to change a bit the reading/writing of the data output. Since this is used by other post-processing routines, I believe it has to be done carefully, keeping `uq` optional.

I think in all cases, best to try keeping `uq` optional and towards more modular. So the code could be easily maintained / replaced if need.

**Comment by alexlib** [comment]
See my first attempt 
https://github.com/OpenPIV/openpiv-python/pull/238

**Comment by alexlib** [comment]
Please correct stuff, as I probably didn't do it well, e.g. the grid is rather coarse

**Comment by lento234** [comment]
@alexlib sure. I'll modify it now and do a pr. I think I will do a direct UQ, instead of the step-by-step approach with intermediate warping step. It is the easiest and the simplest way of obtaining the UQ.

* A direct UQ would be through: `pivuq.disparity.sws`, and the input is just the image pair, and the PIV vector field. 
* Alternatively, a step-by-step approach includes: (1) warping using `pivuq.warp`, it will output the warped image pair. (2) then you pass it into `pivuq.lib.disparity_vector_computation` which will output the raw disparity values `D` and peaks `c` without any grid statistics.  (3) Finally, you would do the ensemble statistics using `pivuq.lib.disparity_ensemble_statistics` to calculate the windowed disparity field. The last step outputs `delta`, `mu`, `N`, and `sigma` described in the original paper. FYI, the direct UQ is just a wrapper for these sub steps.

Couple of things to note:
* I did disparity at the pixel-level, so the output will be the size of the image. If need, I can implement a sub-sampling option, to output the same dimension as the input PIV vector field. 
* I made a mistake before. The data file you mentioned in the other issue, the `x` and `y` indicates the image coordinates, not the real coordinates. Though, I don't think matter anyway. 

Best,
Lento
