### ISSUE TITLE
Documentation not synchronized

### ISSUE THREAD

**Issue by ZLoverty** [OpenPIV/openpiv-python#270]
**Describe the bug**

The syntax of `validation.sig2noise_val()` has been modified. The return value now is only the mask, instead of (u, v, mask). This change is reflected in the tutorial notebook1 in this repo, but the [documentation website](https://openpiv.readthedocs.io/en/latest/src/tutorial1.html) is not yet modified. This might confuse new users.

**To Reproduce**

1. Go to [documentation website](https://openpiv.readthedocs.io/en/latest/src/tutorial1.html) and you will see it. 

**Expected behavior**

Documentation reflects the up-to-date syntax. I would also suggest that we keep the syntax unchanged, unless it is necessary.

**Screenshots** (from the documentation website)

![image](https://user-images.githubusercontent.com/20690573/203116673-3d01e027-41e4-4f4c-9af2-293ac98ce57e.png)

**Comment by alexlib** [comment]
thanks. please check again, it's rebuilt @ZLoverty

**Comment by Fellypao** [comment]
Hi,
You have updated the docs in https://openpiv.readthedocs.io/en/latest/src/tutorial1.html according to version 0.24.4 
However, the latest release remains at 0.24.2 (in both [pypi](https://pypi.org/project/OpenPIV/) and [github](https://github.com/OpenPIV/openpiv-python)). Version 0.22.4 is tagged as "pre-release" [here](https://github.com/OpenPIV/openpiv-python/releases). So, the documentation remains not synchronized for the end user (considering that most of them will not build openpiv from sources).

**Comment by alexlib** [comment]
what is needed? to create 0.25 release and stnc everything?

**Comment by Fellypao** [comment]
Well, this is one of the possible solutions.

Another solution would be to provide links to the documentation for previous versions. This is a good solution, from my point of view, because some users maybe binded to any specific version (for several reasons) and then to have access to documentation of different versions would help al lot. 

By the way, this (other) issue with absence of docs for older versions is as common as people not always using the latest version of a given software.

**Comment by alexlib** [comment]
see #279
