### ISSUE TITLE
Multi-grid window deformation algorithm tutorial not working with conda installation

### ISSUE THREAD

**Issue by Colin-Gnt** [OpenPIV/openpiv-python#323]
**Describe the bug**
The package installed with conda ("conda install -c alexlib openpiv") as it is written in the documentation is not the same as the one in git.
As a result, windef is not working as it should (can't make the tutorial working)

Can be fixed by installing openpiv with the command:
`conda install -c openpiv openpiv`

Maybe it is just a problem of a version and the documentation could just be updated ? 
**To Reproduce**
1. install openpiv as it is shown in the documentation with conda :
`conda install -c alexlib openpiv`
2. Run the 'multi-grid window deromation tutorial'
3. Errors in the code (no definition of the class 'PIVSettings' in windef.py

**Expected behavior**
Tutorial working

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by ErichZimmer** [comment]
I tried to recreate the issue, but it appears that my conda client cannot recognize the channels for both openpiv and alexlib. This was for both python 3.8, 3.10, and 3.12 with conda 4.12.0 on Windows 11. I will try again later this week, but your issue seems to be a version compatibility conflict. If I remember right, `conda install -c alexlib openpiv` was created for compatibility reasons due to [openpiv_tk_gui](https://github.com/OpenPIV/openpiv_tk_gui) using an older version of OpenPIV (which was recently updated last week), but I may be wrong since I am not up to date with recent changes in OpenPIV.

**Comment by alexlib** [comment]
> **Describe the bug** The package installed with conda ("conda install -c alexlib openpiv") as it is written in the documentation is not the same as the one in git. As a result, windef is not working as it should (can't make the tutorial working)
> 
> Can be fixed by installing openpiv with the command: `conda install -c openpiv openpiv`
> 
> Maybe it is just a problem of a version and the documentation could just be updated ? **To Reproduce** Steps to reproduce the behavior:
> 
> 1. install openpiv as it is shown in the documentation with conda :
>    `conda install -c alexlib openpiv`
> 2. Run the 'multi-grid window deromation tutorial'
> 3. Errors in the code (no definition of the class 'PIVSettings' in windef.py
> 
> **Expected behavior** Tutorial working
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu 22.04

see the last commit
